project:
  type: website
    
    
execute:
  freeze: true  # Re-render only when source changes

bibliography: /Users/juan/Dropbox/refs/zotero-master.bib
link-citations: false
csl: files/bib/chicago-syllabus-no-bib.csl

description-meta: "Course site for my civil wars class."

website:
  title: "Civil wars"
  search: false
  site-url: "https://civwar.juanftellez.com"

  navbar:
    pinned: true
    right:
      - text: "Syllabus"
        file: index.qmd
      - text: "Schedule"
        file: schedule.qmd
      - text: "Assignments"
        file: assignment/index.qmd

  sidebar: 
  - title: "Assignments"
    style: "docked"
    search: false
    background: dark
    contents: 
      - section: "Overview"
        contents:
          - assignment/index.qmd
  
  - title: "Content"
    style: "docked"
    search: false
    background: dark
    contents: 
       section: "Class materials"
       contents:
          - content/01-content.qmd
          - content/02-content.qmd
          - content/03-content.qmd
          - content/04-content.qmd
          - content/05-content.qmd
          - content/06-content.qmd
          - content/07-content.qmd
          - content/08-content.qmd
          - content/09-content.qmd
          - content/10-content.qmd

  page-footer:
    left: |
      Content {{< fa copyright >}} {{< var course.copyright_year >}} by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}}) <br>
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})

format:
  html:
    theme: html/custom.scss
    anchor-sections: false
    toc: true
    css: html/tenso-berkeley.css
