project:
  type: website
    
    
execute:
  freeze: true  # Re-render only when source changes

bibliography: /Users/juan/Dropbox/refs/zotero-master.bib
link-citations: true
#csl: files/bib/chicago-syllabus-no-bib.csl

description-meta: "Course site for my civil wars class."

website:
  title: "Civil wars"
  search: false
  site-url: "https://civwar.juanftellez.com"

  navbar:
    pinned: true
    right:
      - text: "Syllabus"
        file: index.qmd
      - text: "Schedule"
        file: schedule.qmd
      - text: "Assignments"
        file: assignment/index.qmd

  page-footer:
    left: |
      Content {{< fa copyright >}} {{< var course.copyright_year >}} by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}}) <br>
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})

format:
  html:
    theme: html/custom.scss
    anchor-sections: false
    toc: true
    css: html/tenso-berkeley.css
